version: "3.9"

services:
  l22:
    image: hkim0331/clojure
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:cached
      - m2:/root/.m2
    working_dir: /usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
  m2:
    external: true
