version: "3"

services:
  luminus:
    image: hkim0331/l22:0.1
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    working_dir: /usr/src/app
    entrypoint:
      - sleep
      - infinity

  db:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_DB: l22
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  gitlibs:
    external: true
  m2:
    external: true
