version: "3.3"

services:
  luminus:
    image: hkim0331/luminus
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    working_dir: /usr/src/app
    # command: /bin/sh -c "while sleep 1000; do :; done"
    entrypoint:
      - sleep
      - infinity

  db:
    image: postgres:14.8
    restart: always
    environment:
      POSTGRES_DB: py99
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    # ports:
    #   - "55432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  gitlibs:
    external: true
  m2:
    external: true
